# Generated by Django 5.0.3 on 2024-05-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='xlsx_file',
            field=models.FileField(blank=True, null=True, upload_to='xlsx_files/'),
        ),
    ]
