# Generated by Django 5.0.3 on 2024-05-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_task_xlsx_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='important',
        ),
        migrations.AlterField(
            model_name='task',
            name='xlsx_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
