# Generated by Django 5.0.3 on 2024-05-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_remove_task_important_alter_task_xlsx_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='xlsx_file',
            new_name='data_file',
        ),
    ]
