# Generated by Django 5.0.6 on 2024-06-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0004_rename_xlsx_file_task_data_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='datecompleted',
        ),
    ]
