# Generated by Django 5.0.6 on 2024-08-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
